name: Publish Blog 

on:
  push:
    branches: [ master ]

jobs:
  build-n-publish:
    name: Build and Publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Publish to gh-page
        run: |
          git config user.name 'GitHub Actions'
          git config user.email github-actions@github.com
          invoke gh-pages
