name: Publish Blog 

on:
  push:
    branches: [ master ]

jobs:
  build-n-publish:
    name: Build and Publish
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Initialize Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Publish gh-page
        run: invoke gh-pages
